databases:
  - name: remixdb
    databaseName: remixdb
    user: remix

services:
  - type: web
    name: remix
    env: node
    buildCommand: "npm install && npx prisma migrate deploy"
    startCommand: "npm run start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: remixdb
          property: connectionString